# Generated by Django 2.2.7 on 2019-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191115_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(default='', upload_to='blogs/images/'),
            preserve_default=False,
        ),
    ]
